### ISSUE TITLE
[BUG] Unable to compile version 2.9.0

### ISSUE THREAD

**Issue by jonsamwell** [TinkoffCreditSystems/taiga-ui#400]
# 🐞 Bug report

### Description

After upgrading to 2.9.0 I get the below errors when compiling my application.

```
Compiling TypeScript sources through NGC
ERROR: node_modules/@taiga-ui/core/components/dialog/dialog.service.d.ts:8:47 - error TS2307: Cannot find module '../../../../dist/core/types/dialog-options' or its corresponding type declarations.

    protected readonly defaultOptions: import("../../../../dist/core/types/dialog-options").TuiDialogBaseOptions & {
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

An unhandled exception occurred: node_modules/@taiga-ui/core/components/dialog/dialog.service.d.ts:8:47 - error TS2307: Cannot find module '../../../../dist/core/types/dialog-options' or its corresponding type declarations.

    protected readonly defaultOptions: import("../../../../dist/core/types/dialog-options").TuiDialogBaseOptions & {
```

### Expected behavior

To compile without error

### Versions

-   OS: Windows
-   Browser N/A
-   Angular  12
-   Package @taiga-ui/core@2.9.0 

### Additional context

Tried deleting the node_modules folder and package-lock.json to no avail

Package.json
```
  "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/cdk": "^12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@microsoft/signalr": "^5.0.3",
    "@ng-web-apis/common": "^1.9.0",
    "@ngx-formly/core": "^6.0.0-next.1",
    "@ngx-formly/schematics": "^6.0.0-next.1",
    "@stripe/stripe-js": "^1.14.0",
    "@taiga-ui/addon-charts": "^2.9.0",
    "@taiga-ui/addon-table": "^2.9.0",
    "@taiga-ui/cdk": "^2.9.0",
    "@taiga-ui/core": "^2.9.0",
    "@taiga-ui/icons": "^2.9.0",
    "@taiga-ui/kit": "^2.9.0",
    "@tinkoff/ng-dompurify": "^3.0.0",
    "browser-image-compression": "^1.0.14",
    "dompurify": "^2.2.7",
    "rxjs": "~6.6.7",
    "tslib": "^2.1.0",
    "uuid": "^8.3.2",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.0",
    "@angular-eslint/builder": "^12.0.0",
    "@angular-eslint/eslint-plugin": "^12.0.0",
    "@angular-eslint/eslint-plugin-template": "^12.0.0",
    "@angular-eslint/schematics": "12.0.0",
    "@angular-eslint/template-parser": "^12.0.0",
    "@angular/cli": "^12.0.0",
    "@angular/compiler-cli": "~12.0.0",
    "@types/dompurify": "^2.2.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "4.23.0",
    "@typescript-eslint/parser": "4.23.0",
    "cross-env": "^7.0.3",
    "eslint": "^7.26.0",
    "eslint-plugin-etc": "^1.4.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "gulp": "^4.0.2",
    "gulp-debug": "^4.0.0",
    "gulp-replace": "^1.1.2",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^12.0.0",
    "protractor": "~7.0.0",
    "source-map-explorer": "^2.5.2",
    "tailwindcss": "^2.0.3",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  }
```

**Comment by waterplea** [comment]
Yes, sorry about that, rushed a fix for webpack 5 and Angular 12 — for some reason script that we have that was supposed to catch such things didn't trigger. I'll release a new version soon.

**Comment by jonsamwell** [comment]
Many thanks compiling well now!
